# Generated by Django 5.2 on 2026-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="feature",
            field=models.BooleanField(
                default=False, help_text="Mark as featured product"
            ),
        ),
    ]
