# Generated by Django 5.2 on 2026-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload product image",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
