# Generated by Django 5.2 on 2026-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_image_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Product size (e.g., S, M, L, XL, 42, 44)",
                max_length=50,
            ),
        ),
    ]
